pharmacy/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('relation/',views.relation,name='relation'),
    path('orders/',views.orders,name='orders'),
    path('reset/',views.UserPassReset.as_view(),name='reset_pass'),
    path('reset/done',views.PasswordResetDone.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('confirm/done/',views.PasswordResetComplete.as_view(),name='password_reset_complete'),
]

pharmacy/cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns = [
    path('',views.detail, name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
]

pharmacy/pharmacy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('report/',include('report.urls',namespace='report')),
    path('',include('medicine.urls',namespace='medicine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pharmacy/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import MyUserManager



class User(AbstractBaseUser):
    email= models.EmailField(max_length=100,unique=True,verbose_name='ایمیل')
    full_name= models.CharField(max_length=100,verbose_name='نام کامل')
    is_admin= models.BooleanField(default=False,verbose_name='ادمین بودن')
    is_active = models.BooleanField(default=True,verbose_name='فعال بودن')
    phone_number=models.IntegerField(blank=True,null=True,default=0,verbose_name='شماره تلفن')
    objects=MyUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    class Meta:
        verbose_name= 'کاربر'
        verbose_name_plural='کاربران'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

pharmacy/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField



class UserCreationForm(forms.ModelForm):
    password1=forms.CharField(label='password',widget=forms.PasswordInput)
    password2=forms.CharField(label='confirm password',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields =('email','full_name')

    def clean_password2(self):
        cd=self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] !=cd['password2']:
            raise forms.ValidationError('password must match')
        return cd['password2']

    def save(self, commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password=ReadOnlyPasswordHashField()

    class Meta:
        model=User
        fields=('email','password','full_name')

    def clean_password(self):
         return self.initial["password"]

class UserLoginForm(forms.Form):
    email=forms.EmailField(label='ایمیل',widget=forms.EmailInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='پسورد',widget=forms.PasswordInput(attrs={'class':'form-control'}))

class UserRegisterForm(forms.Form):
    email=forms.EmailField(label='ایمیل',widget=forms.EmailInput(attrs={'class':'form-control'}))
    full_name=forms.CharField(label='نام کامل',widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='پسورد',widget=forms.PasswordInput(attrs={'class':'form-control'}))

class UserEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('full_name','phone_number')

pharmacy/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import UserLoginForm,UserRegisterForm,UserEditForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import User
from orders.models import Order
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


def user_login(request):
    if request.method == 'POST':
        form=UserLoginForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user=authenticate(request,email=cd['email'], password=cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request,'you logged in succesfully','success')
                return redirect('medicine:home')
            else:
                messages.error(request,'username or pass is wrong','danger')
    else:
        form=UserLoginForm()
    return render(request,'accounts/login.html',{'form':form})


def user_logout(request):
    logout(request)
    messages.success(request,'you logged out succesfully','success')
    return redirect('medicine:home')


def user_register(request):
    if request.method == 'POST':
        form=UserRegisterForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user=User.objects.create_user(cd['email'],cd['full_name'],cd['password'])
            user.save()
            messages.success(request,'you registerd succesfully','success')
            return redirect('accounts:login')
    else:
        form=UserRegisterForm()
    return render(request,'accounts/register.html',{'form':form})



def profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST , instance=user)
        if form.is_valid():
            user = form.save()
            messages.success(request,'اطلاعات با موفقیت ویرایش شد','success')
            return redirect('accounts:profile')
    form = UserEditForm(instance=user)
    return render(request,'accounts/profile.html',{'form':form ,'user':user})


def relation(request):
    return render(request,'accounts/relation.html')


def orders(request):
    orders = Order.objects.filter(user=request.user)
    return render(request,'orders/orders_list.html',{'orders':orders})


class UserPassReset(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'

class PasswordResetDone(auth_views.PasswordResetDoneView):
    template_name = 'accounts/reset_done.html'

class PasswordResetConfirm(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')

class PasswordResetComplete(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

pharmacy/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}ورود{% endblock %}
{% block content %}
    <p>فرم ورود </p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary" value="ورود">
    </form>
    <a href="{% url 'accounts:reset_pass' %}">فراموشی رمز عبور</a>
{% endblock %}

pharmacy/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}باریابی رمز عبور{% endblock %}
{% block content %}
    <p>پسورد شما با موفقیت تغییر یافت  </p>
{% endblock %}

pharmacy/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}باریابی رمز عبور{% endblock %}
{% block content %}
    {% if validlink %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="تغییر">
        </form>
    {% else %}
        <p>این لینک معتبر نیست دوباره تلاش کنید</p>
    {% endif %}
{% endblock %}

pharmacy/accounts/templates/accounts/password_reset_email.html
برای بازیابی رمز عبور از سایت داروخانه این ایمیل <<{{ email }}>> وارد شده است در صورت تایید روی لینک زیر برای بازیابی رمز عبور خود کلیک کنید
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

pharmacy/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block title %}باریابی رمز عبور{% endblock %}
{% block content %}
    <p>لطفا ایمیل خود را برای بازیابی رمز وارد کنید </p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="ارسال">
    </form>
{% endblock %}

pharmacy/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}پروفایل{% endblock %}
{% block content %}
    <p>اطلاعات  </p>
    <p>ایمیل {{ user.email }}</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="ویرایش">
    </form>
{% endblock %}

pharmacy/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %}ثبتنام{% endblock %}
{% block content %}
    <p>فرم ثبتنام</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary" value="ثبتنام">
    </form>
{% endblock %}

pharmacy/accounts/templates/accounts/relation.html
{% extends 'base.html' %}
{% block title %}پروفایل{% endblock %}
{% block content %}
    <p>  ارتباط با ما</p>
    <p> تلگرام : آیدی تلگرام</p>
    <p>ایمیل: آدرس ایمیل</p>
{% endblock %}

pharmacy/accounts/templates/accounts/reset_done.html
{% extends 'base.html' %}
{% block title %}باریابی رمز عبور{% endblock %}
{% block content %}
    <p>یک لینک به ایمیل شما ارسال شد لطفا ان را چک کنید </p>
{% endblock %}