pharmacy/cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns = [
    path('',views.detail, name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
]

pharmacy/pharmacy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('report/',include('report.urls',namespace='report')),
    path('',include('medicine.urls',namespace='medicine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pharmacy/cart/models.py
from django.db import models

# Create your models here.

pharmacy/cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(label='تعداد' , min_value=1,max_value=100)

pharmacy/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import CartAddForm
from .cart import Cart
from medicine.models import Product
from django.views.decorators.http import require_POST
from django.contrib import messages


def detail(request):
    cart = Cart(request)
    return render(request,'cart/detail.html',{'cart':cart})


@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if product.count >= cd['quantity']:
            cart.add(product=product,quantity=cd['quantity'])
            messages.success(request,'با موفقیت به سبد خرید شما اضافه شد','success')
        else:
            messages.error(request,'موجودی کافی نیست','danger')
        return redirect('medicine:product_detail',product.slug)


def cart_remove(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    cart.remove(product)
    messages.success(request,'با موفقیت پاک شد','succuss')
    return redirect('cart:detail')

pharmacy/cart/templates/cart/inc/item_list.html
 <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">محصول</th>
                <th scope="col">تعداد</th>
                <th scope="col">قیمت واحد</th>
                <th scope="col">قیمت کل</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}

            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td><a href="{% url 'cart:cart_remove' item.product.id %}">حذف</a></td>
            </tr>
        {% endfor %}
            <tr>
                <td>کل</td>
                <td colspan="4"></td>
                <td>{{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>