pharmacy/cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns = [
    path('',views.detail, name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
]

pharmacy/medicine/urls.py
from django.urls import path,re_path
from . import views


app_name='medicine'
urlpatterns = [
    path('',views.home,name='home'),
    re_path(r'^category/(?P<slug>[\w-]+)/$',views.home,name='category_filter'),
    re_path(r'^brand/(?P<b_slug>[\w-]+)/$',views.home,name='brand_filter'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.product_detail,name='product_detail'),
    path('search/',views.search,name='search'),
]

pharmacy/pharmacy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('report/',include('report.urls',namespace='report')),
    path('',include('medicine.urls',namespace='medicine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pharmacy/medicine/models.py
from django.db import models
from django.urls import reverse
from django_jalali.db import models as jmodels
from django.conf import settings



class Brand(models.Model):
    name = models.CharField(max_length=200,verbose_name='نام برند')
    slug = models.SlugField(max_length=200 , unique=True ,verbose_name='اسلاگ',allow_unicode=True,)

    class Meta:
        ordering =('name',)
        verbose_name= 'برند'
        verbose_name_plural='برند ها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('medicine:brand_filter',args=(self.slug,))


class Category(models.Model):
    name = models.CharField(max_length=200,verbose_name='نام دسته بندی')
    slug = models.SlugField(max_length=200 , unique=True,verbose_name='اسلاگ',allow_unicode=True)
    sub_category = models.ForeignKey('self',related_name='scategory',on_delete=models.CASCADE,blank=True,null=True,verbose_name='زیر دسته بندی')
    is_sub=models.BooleanField(default=False,verbose_name='زیر دسته بندی بودن')

    class Meta:
        ordering =('name',)
        verbose_name= 'دسته بندی'
        verbose_name_plural='دسته بندی ها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('medicine:category_filter',args=(self.slug,))


class Product(models.Model):
    category= models.ManyToManyField(Category,related_name='products',verbose_name='دسته بندی')
    name = models.CharField(max_length=200,verbose_name='نام محصول')
    slug = models.SlugField(max_length=200 ,unique=True,verbose_name='اسلاگ',allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/',verbose_name='تصویر')
    description = models.TextField(verbose_name='توضیحات')
    price = models.PositiveBigIntegerField(verbose_name='قیمت')
    available = models.BooleanField(default=True,verbose_name='موجود بودن')
    count = models.PositiveBigIntegerField(verbose_name='تاریخ تعداد موجود')
    date_of_manufacture = jmodels.jDateField(verbose_name='تاریخ تولید')
    expiration_date = jmodels.jDateField(verbose_name='تاریخ انقضا')
    created= jmodels.jDateTimeField(auto_now_add=True,verbose_name='تاریخ ایجاد')
    updated = jmodels.jDateTimeField(auto_now=True,verbose_name='تاریخ اپدیت')
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE,related_name='b_product',verbose_name='برند',blank=True,null=True)

    class Meta:
        ordering = ('name',)
        verbose_name= 'محصول'
        verbose_name_plural='محصولات'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('medicine:product_detail',args=(self.slug,))


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='ucomment')
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='pcomment')
    reply = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='rcomment')
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=500)
    created = jmodels.jDateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-{self.body[:30]}'

    class Meta:
        ordering = ('-created',)
        verbose_name= 'نظر'
        verbose_name_plural='نظرات'

pharmacy/medicine/forms.py
from django import forms
from .models import Comment


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =('body',)
        widgets = {
            'body' : forms.Textarea(attrs={'class':'form-content'},)
        }
        labels = {
            'body' : 'متن'
        }
        error_messages ={
            'body':{
                'required':'این فیلد اجباری است',
            }
        }
        help_text ={
            'body': 'حداکثر 500 کاراکتر'
        }


class AddReplytForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =('body',)

pharmacy/medicine/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product,Brand,Comment
from cart.forms import CartAddForm
from django.core.paginator import Paginator
from .forms import AddCommentForm
from django.contrib import messages


def home(request,slug=None,b_slug=None):
    categories=Category.objects.filter(is_sub=False)
    products=Product.objects.filter(available=True)
    brands = Brand.objects.all()
    if slug:
        category=get_object_or_404(Category,slug=slug)
        products=products.filter(category=category)
    elif b_slug:
        brand=get_object_or_404(Brand,slug=b_slug)
        products=products.filter(brand=brand)

    paginator = Paginator(products,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'medicine/home.html',{'categories':categories,'brands':brands ,'page_obj':page_obj})


def product_detail(request,slug):
    product=get_object_or_404(Product,slug=slug)
    if request.method == 'POST':
        comment_form = AddCommentForm(request.POST)
        if comment_form.is_valid():
            new_comment =comment_form.save(commit=False)
            new_comment.product = product
            new_comment.user = request.user
            new_comment.save()
            messages.success(request,'نظر شما با موفقیت ثبت شد','succuss')
    else:
            comment_form= AddCommentForm()
    form =CartAddForm()
    comments = Comment.objects.filter(product=product,is_reply=False)
    paginator = Paginator(comments,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'medicine/product_detail.html',
                  {'product':product,'page_obj':page_obj,'form':form,'comment_form':comment_form})


def search(request):
    data= request.GET.get('search')

    products = Product.objects.filter(name__icontains=data)
    categories = Category.objects.filter(is_sub=False)
    brands = Brand.objects.all()

    paginator = Paginator(products,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'medicine/home.html',{'categories':categories,'brands':brands ,'page_obj':page_obj})

pharmacy/medicine/templates/medicine/home.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}خانه{% endblock %}

{% block head %}

<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}

    <div class="btn-group">
        <a href="{% url 'medicine:home' %}" class="btn btn-primary">برند ها</a>
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </button>
        <div class="dropdown-menu">
            {% for brand in brands %}
                <a class="dropdown-item" href="{{ brand.get_absolute_url }}">{{ brand.name }}</a>
            {% endfor %}
        </div>
    </div>

    {% for category in categories %}

        <div class="btn-group dropstart">
            <a href="{{ category.get_absolute_url }}" class="btn btn-primary">{{ category.name }}</a>
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                {% for sub in category.scategory.all %}
                        <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

<br><br><br>

<div style="width:60%;display:inline-block;border: 5px solid  #5cb5af;">
{% include 'medicine/inc/slide.html' %}
</div>


            <div class="coupon" style="width:30%; height:200px;margin:1%;display:inline-block;border: 5px dotted #5cb5af;">

                <div class="container" style="heigh:100px;">
                    <h5 > gain-bolic-olimp</h5>
                </div>

                <a href="{% url 'medicine:product_detail' 'gain-bolic' %}" >
                    <img src="{% static 'img/gain-bolic-olimp.jpg' %}" alt=" gain-bolic" width="150px" height="150px" margin-top="2%" class="card-img-top" alt="{{ product.name }}"></a>

                <div class="container" style="background-color:white">
                <h2><b>gain-bolic-olimp</b></h2>
                <p>perfect</p>
                </div>
                <div class="container" style="padding:1%;margin-top:2%;">
                    <p>قیمت: <span class="promo"><del style="color:red;">30000</del> 20000</span> تومان</p>

            </div>
        </div>
<br><br>
<div style="border: 5px outset  #e97790;margin-top:100px;padding:5px">
<div style="padding: 30px;text-align: center;background-color:#fec0cd;margin:5% 10%">
    <h3>محصولات   </h3>
</div>
<hr>
    {% for product in products %}
        
            <div class="coupon" style="width:28%; height:320px;display:inline-block;margin:1%">
                <a href="{{ product.get_absolute_url }}" >
                <div class="container" style="heigh:100px;">
                    <h5 > {{ product.name }}</h5>
                </div></a>
                {% thumbnail product.image "200x200" as im %}
                    <img src="{{ im.url }}" width="150px" height="150px" margin-top="2%" class="card-img-top" alt="{{ product.name }}">
                {% endthumbnail %}
                <div class="container" style="background-color:white">
                <h2><b></b></h2>
                <p></p>
                </div>
                <div class="container" style="padding:1%;margin-top:2%;">
                {% if product.discount == 0 %}
                    <p>قیمت: <span class="promo">{{ product.price }}</span> تومان</p>
               {% else %}
                    <p>قیمت: <span class="promo"><del style="color:red;">{{ product.price }}</del> {{ product.get_discount_price}}</span> تومان</p>
                {% endif %}

            </div>
        </div>

    {% endfor %}
</div>

 

  <div style="margin:70px  20% 70px 20%;padding:10px;border: 5px ridge  #eeb156;">
    <img src="{% static 'img/Instagram-profile-photos-1.jpg' %}" alt="Avatar" style="width:300px;height:300px;float:left;">
    <div style="padding-bottom: 120px;">
    <h1>مژده مژده</h1> 
        <h4>صفحه اینستاگرام</h4> 
        <p>به صفحه اینستاگرام داروخانه نیکو بپیوندید.
            جهت بهره مندی از کد های تخفیف تا سقف 50 درصد برای محصولات آرایشی و بهداشتی می توانید به عضو پیج اینستگرام داروخانه نیکو شوید.</p>
        <p>@drug_store_rajaee</p>
        </div>
  </div>
{% endblock %}

pharmacy/medicine/templates/medicine/product_detail.html
{% extends 'base.html' %}
{% block title %}detail{% endblock %}
{% block content %}

<img src="{{ product.image.url }}"  alt="{{ product.name }}" class="float-right" style="width:30%;heigh:500px;margin:2%;">
<div style="margin-bottom:350px;margin-top:2%">
<h5 >{{ product.name }}</h5>
        <p >توضیحات: {{ product.description }}</p>
        <p ><small class="text-muted">تولید: {{ product.date_of_manufacture }} </small></p>
          <p ><small class="text-muted">انقضا: {{ product.expiration_date }}</small></p>
          <p ><small class="text-muted"> قیمت :{{ product.price }} تومان</small></p>

</div>
     {% if request.user.is_authenticated %}
    <form action="{% url 'cart:cart_add' product.id %}" method="post" style="margin-top:2%;">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="افزودن به سبد خرید">
    </form>



    <form action="" method="post" style="margin-top:2%;">
        {% csrf_token %}
        {{ comment_form }}
        <br>
        <input type="submit" value="افزودن نظر ">
    </form>
    {% else %}
        <p>تنها کاربران میتوانند نظر بدهند</p>
    {% endif %}

     {% with total=page_obj.paginator.count %}
        <p>برای این محصول {{ total }} نظر وجود داره</p>
    {% endwith %}

{% for comment in page_obj %}
        <div class="card" style="background-color:#fec0cd;padding:2%">
            <p class="card-header" >{{ comment.user }}</p>
            <p class="card-body">{{ comment.body }}</p><small>{{ comment.created}}</small>
            {% for reply in comment.rcomment.all %}
                <p class="bg-primary text-white p-3 m-5">{{ reply.user}}<br>{{ reply.body}}</p>
            {% endfor %}
        </div>
    {% empty %}
        <p>کامنتی وجود ندارد</p>
    {% endfor %}

    {% include 'medicine/inc/pagination.html' %}
{% endblock %}