pharmacy/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('relation/',views.relation,name='relation'),
    path('orders/',views.orders,name='orders'),
    path('reset/',views.UserPassReset.as_view(),name='reset_pass'),
    path('reset/done',views.PasswordResetDone.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('confirm/done/',views.PasswordResetComplete.as_view(),name='password_reset_complete'),
]

pharmacy/cart/urls.py
from django.urls import path
from . import views


app_name='cart'
urlpatterns = [
    path('',views.detail, name='detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
]

pharmacy/medicine/urls.py
from django.urls import path,re_path
from . import views


app_name='medicine'
urlpatterns = [
    path('',views.home,name='home'),
    re_path(r'^category/(?P<slug>[\w-]+)/$',views.home,name='category_filter'),
    re_path(r'^brand/(?P<b_slug>[\w-]+)/$',views.home,name='brand_filter'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.product_detail,name='product_detail'),
    path('search/',views.search,name='search'),
]

pharmacy/orders/urls.py
from django.urls import path,re_path
from . import views


app_name='orders'
urlpatterns = [
    path('create/',views.order_create,name='create'),
    path('<int:order_id>/',views.detail,name='detail'),
    path('payment/<int:order_id>/<price>',views.payment , name='payment'),
    path('verify/',views.verify , name='verify'),
    path('apply/<int:order_id>/',views.coupon_apply,name='coupon_apply'),
    path('order_detail/<int:order_id>/',views.order_detail,name='order_detail'),
    path('order_remove/<int:order_id>/',views.order_remove,name='order_remove'),
    # re_path(r'^report/(?P<type>(y|m|d)?)/<int:time>/$',views.report , name ='report'),
    re_path(r'^report/$',views.report , name ='report'),
]

pharmacy/pharmacy/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('report/',include('report.urls',namespace='report')),
    path('',include('medicine.urls',namespace='medicine')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pharmacy/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}" style="font-family: lalezar;">{{ msg }}</p>
    {% endfor %}
{% endif %}

pharmacy/templates/inc/navbar.html

<div class="clearfix" style="background-color:#27519b;text-align: center;font-family: lalezar;">
  <a class="navbar-brand" href="{% url 'medicine:home' %}"><h1 style="text-align: center;color:white;">داروخانه نیکو</h1></a>
</div>
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #3f9fd2;font-family: lalezar;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'medicine:home' %}">صفحه اول</a>
        </li>
         {%  if request.user.is_authenticated %}

        <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">کاربر</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'accounts:profile' %}">مشاهده پروفایل</a>
      <a class="dropdown-item" href="{% url 'accounts:reset_pass' %}">تغییر رمز عبور</a>
      <a class="dropdown-item" href="{% url 'accounts:orders' %}">سفارش های من</a>
      <a class="dropdown-item" href="{% url 'cart:detail' %}">سبد خرید</a>
      <div class="dropdown-divider"></div>
      {% if request.user.is_admin %}
        <a class="dropdown-item" href="{% url 'report:report' %}">گزارش</a>
      {% else %}
        <a class="dropdown-item" href="{% url 'accounts:relation' %}">ارتباط با ما</a>
      {% endif %}
         </div>
  </li>
          <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
  </li>

    {% else %}
    <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
    </li>
    <li class="nav-item"  >
    <a class="nav-link" href="{% url 'accounts:register' %}">ثبتنام</a>
    </li>
    {% endif %}


      </ul>


    </div>
  </div>
  <form class="d-flex" dir="ltr" action="{% url 'medicine:search' %}">
        <input class="form-control me-2" type="search" placeholder="جستجو" aria-label="Search"  name="search">
        <button class="btn btn-outline-success" type="submit">جستجو</button>
      </form>
</nav>
